name = "shadow-traffic"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
node_compat = true

[vars]
PROD_BASE = "https://api.pocketnode.app"
SHADOW_BASE = "https://api.test.server.pocketnode.app"
