name = "shadow-traffic"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
node_compat = true

[vars]
RATE = 100

# TODO: Change parmaeters below! 
PROD_BASE = "https://example.com"
SHADOW_BASE = "https://example.com"
IGNORED_PATHS = ["/favicon.ico", "/ignored_path"]
